import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FontAwesomeModule,
  FaIconLibrary,
} from '@fortawesome/angular-fontawesome';
import {
  faUserEdit,
  faInfoCircle,
  faQuoteRight, 
  faUser,
  faCar,
  faCreditCard,
  faLayerGroup,
  faRedo,
  faEye,
  faAt,
  faEyeSlash,
  faSignInAlt,
  faSignOutAlt,
  faUserCheck,
  faCheckDouble,
  faHome,
  faGlobeAfrica,
  faMoneyCheckAlt,
  faFileInvoice,
  faListAlt,
  faCheck,
  faUpload,
  faQuestion,
  faCarAlt,
  faClipboardList,
  faUserCog,
  faForward,
  faDotCircle,
  faCircle,
  faPlusCircle,
  faMinusCircle,
  // faEyeDropper,
  faKey,
  faSort,
  faBars,
  faTimesCircle,
  faEdit,
  faSave,
  faUndo,
  faShoppingCart,
  faCartPlus,
  faPlus,
  faTimes,
  faArrowRight,
  faTrash,
  faFileUpload,
  faList,
  faArrowDown,
  faArrowUp,
  faComment,
  faCalendarWeek,
  faSyncAlt,faArrowLeft, faCheckCircle, faExclamationCircle, faWindowClose, faMoneyCheck,
  faAdjust,faTasks,faClipboardCheck,faClock, faMinus
  , faDownload,
  faCheckSquare,
  faCarSide,
  faFileMedicalAlt,
  faStethoscope,
  faPlaneDeparture,faArrowCircleLeft,faArrowCircleRight,
  faExclamationTriangle,
  faMapMarker,
  faSortAmountUp,
  faSortAmountDown,
  faHourglassHalf,
  faPhone,
  faFax,
  faClone,
  faUserCircle,
  faUserTie,
  faFileInvoiceDollar,
  faPrint,
  faMoneyBill,
  faMoneyBillAlt,
  faHandshake,
  faCogs,
  faCaretLeft,
  faShare,
  faRetweet,
  faPlusSquare,
  faCaretUp,
  faCaretDown,
  faIdCard
  
} from '@fortawesome/free-solid-svg-icons';

import {
  faFacebookSquare,
  faYoutube,
  faTwitterSquare,
  faLinkedin,
} from '@fortawesome/free-brands-svg-icons';

@NgModule({
  declarations: [],
  imports: [CommonModule, FontAwesomeModule],
  exports: [FontAwesomeModule],
})
export class IconsModule {
  constructor(library: FaIconLibrary) {

    library.addIcons(faUserEdit,faClipboardCheck,faClock,
      faTasks,
      faInfoCircle,
      faQuoteRight, 
      faAdjust,
      faUser,
      faCar,
      faPlusCircle,
      faMinusCircle,
      faCreditCard,
      faLayerGroup,
      faRedo,
      faEye,
      faEyeSlash,
      faSignInAlt,
      faArrowDown,
      faArrowUp,
      faSignOutAlt,
      faUserCheck,
      faCheckDouble,
      faHome,
      faGlobeAfrica,
      faMoneyCheckAlt,
      faFileInvoice,
      faListAlt,
      faQuestion,
      faFacebookSquare,
      faYoutube,
      faTwitterSquare,
      faLinkedin,
      faCarAlt,
      faClipboardList,
      faUserCog,
      faForward,
      faDotCircle,
      faCheck,
      faUpload,
      faFileInvoice,
      faFileInvoice,
      faCircle,
      faTimesCircle,
      faEdit,
      faSave,
      faUndo,
      faShoppingCart,
      faCartPlus,
      faPlus,
      faTimes,
      faArrowRight,
      faMoneyCheckAlt,
      faTrash,
      faFileUpload,
      faList,faComment,
      faCalendarWeek,
      faCalendarWeek,
      faSyncAlt,faArrowLeft,
      faCheckCircle,
      faExclamationCircle,
      faWindowClose,
      faMoneyCheck,
      faMinus,
      faDownload,faCheckSquare,
      faCarSide,
      faFileMedicalAlt,
      faStethoscope,
      faPlaneDeparture,faArrowCircleLeft,faArrowCircleRight,
      faExclamationTriangle,
      faAt,
      faEyeSlash,
      faSort,
      faSortAmountUp,
      faSortAmountDown,
      faHourglassHalf,
      faBars,
      faKey,
      faPhone,
      faMapMarker,
      faFax,
      faClone,
      faUserCircle,
      faUserTie,
      faFileInvoiceDollar,
      faPrint,
      faMoneyBill,
      faMoneyBillAlt,
      faHandshake,
      faCogs,
      faCaretLeft,
      faCogs,
      faShare,
      faRetweet,
      faPlusSquare,
      faCaretUp,
      faCaretDown,
      faIdCard   
    );
  }
}
